name: desktop_lyric
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  ffi: ^2.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  win32: ^5.15.0
  window_manager: ^0.5.1
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  json_serializable: ^6.12.0
  analyzer: ^10.0.1

flutter:
  uses-material-design: true
